version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 2080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ./../pluginwp:/var/www/html/wp-content/plugins/loonity

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:



#   Tobias Zimmermann
# 11:39
# wp theme install storefront --activate
# wp config create --dbname=<dbname> --dbuser=<dbuser> [--dbpass=<dbpass>]
# wp db create
# Tobias Zimmermann
# 11:40
# wp core install --url=wpclidemo.dev --title="WP-CLI" --admin_user=wpcli --admin_password=wpcli --admin_email=info@wp-cli.org